export const IconNames = {
  eye: "mdiEye",
  eyeOff: "mdiEyeOff",
  close: "mdiClose",
  option: "mdiCog",
  send: "mdiSend",
  pencil: "mdiPencil",
  emoticon: "mdiEmoticon",
  bold: "mdiFormatBold",
  italic: "mdiFormatItalic",
  magnify: "mdiMagnify",
  strikethrough: "mdiFormatStrikethroughVariant",
  link: "mdiLink",
  minus: "mdiMinus",
  listBulleted: "mdiFormatListBulleted",
  title: "mdiFormatTitle",
  numeric1: "mdiNumeric1Circle",
  numeric2: "mdiNumeric2Circle",
  numeric3: "mdiNumeric3Circle",
  numeric4: "mdiNumeric4Circle",
  numeric5: "mdiNumeric5Circle",
  numeric6: "mdiNumeric6Circle",
  numeric7: "mdiNumeric7Circle",
  numeric8: "mdiNumeric8Circle",
  numeric9: "mdiNumeri19Circle",
  numericPlus: "mdiNumeric9PlusCircle",
};
