// Da definire
export const darkTheme = {
  text: "#fff",
  actionText: "#fff",
  scrollbar: "#fff",
  buttonBg: "#101010",
  link: "#0000FF",
  boxShadowPrimary: "#5C5E60",
  boxShadowSecondary: "none",
  dialogBg: "#1D1E20",
  backdrop: "#00000037",

  loginFieldBg: "#3D3F41",
  loginBg: "#1D1E20",

  chatBackground: "#3D3F41",

  textPrimary: "#fff",
  textSecondary: "#F2F4F7",

  snackbarBg: "#1D1E20",
  snackbarText: "#fff",
  error: "#fe354b",
  warning: "#f7a635",
  info: "#206cf7",

  initialsText: "#fff",
  statusBorder: "#fff",
  avatarBg0: "#008A33",
  avatarBg1: "#005B13",
  avatarBg2: "#EF2C49",
  avatarBg3: "#CF173A",
  avatarBg4: "#F0981D",
  avatarBg5: "#CF7A04",
  avatarBg6: "#003366",
  avatarBg7: "#5C5E60",
  onlineStatus: "#68c47e",
  offlineStatus: "#dbdde0",

  iconColor: "#fff",

  buttonText: "#fff",
  buttonBorder: "none",
  buttonConfirmBg: "#456595",
  buttonUndoBg: "#dc2042",

  inputText: "#fff",
  placeholder: "#F2F4F7",
  inputBackground: "#1D1E20",
  inputBorder: "#B7B9BD",
  inputFocusedBorder: "#fff",

  tooltipBg: "#206cf7",
  tooltipText: "#fff",

  headerBg: "#1D1E20",
  headerColor: "#fff",

  messageSenderBg: "#206cf7",
  messageSenderText: "#fff",
  messageReceiverBg: "#fff",
  messageReceiverText: "#000",
  messageSenderNameText: "#0000FF",
  deletedMessageText: "#fff",
  modifiedMessageText: "#fff",
  timestampMessageTextSender: "#F2F4F7",
  timestampMessageTextReceiver: "#000",
  datetimeMessageBg: "#fff",
  datetimeMessageText: "#000",
  messageMenuBg: "#1D1E20",
  messageMenuBgHover: "#6F7174",

  sidebarBg: "#3D3F41",
  sidebarSeparator: "#fff",
  sidebarNoResults: "#F2F4F7",
  conversationChatName: "#fff",
  conversationLastMessageText: "#F2F4F7",
  conversationLastMessageLinkText: "#D3D3D3",
  conversationLastMessageLinkTextHover: "#fff",
  conversationTimestapText: "#fff",
  conversationUnreadMessageCounter: "#0DA2FF",
  conversationUnreadMessageText: "#3AB3FF",
  conversationHoverBg: "#5C5E60",
  conversationActiveBg: "#1D1E20",

  inputControlsBg: "red",
  editorInputBg: "#1D1E20",

  circularProgressBarProgress: "#fff",
  circularProgressBarBackground: "#3D3F41",
};
