version: "3.9"
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: infolab-pg
    volumes:
      - infolab-pg:/var/lib/postgresql/data
    networks:
      - infolab-pg

  db-administration:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: user@user.com
      PGADMIN_DEFAULT_PASSWORD: password
    networks:
      - infolab-pg

networks:
  infolab-pg: {}

volumes:
  infolab-pg: {}